[project]
name = "python"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ldap3>=2.9.1",
    "pycryptodome>=3.23.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "python-dotenv>=1.2.1",
]
